### ISSUE TITLE
There is an error generating keys for the game Riding Extreme 3D

### ISSUE THREAD

**Issue by daviidglz** [ShafiqSadat/HamsterKeyGenWeb#4]
At the end when it finishes generating codes, the codes doesnt't appear. 
<img width="355" alt="error" src="https://github.com/user-attachments/assets/935227b7-dea3-4a9d-822e-cd4b9cb80908">

**Comment by infoward** [comment]
Same issue

**Comment by ShafiqSadat** [comment]
Fixed!
