### ISSUE TITLE
I update it just now it gets 1- too many registers 2- promo code an empty string

### ISSUE THREAD

**Issue by poria129** [ShafiqSadat/HamsterKeyGenWeb#6]
{error_code: "TooManyRegister", error_message: "Register event timeout"}
error_code: "TooManyRegister"
error_message: "Register event timeout"

---------------
{promoCode: ""}
promoCode: ""

---------------
A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request .
To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.
Note that if an opaque response is sufficient, the request's mode can be set to no-cors to fetch the resource with CORS disabled; that way CORS headers are not required but the response content is inaccessible (opaque).

**Comment by Frahane** [comment]
Generating CLONE Keys are tough, I have been able to get 2 keys out of 10. Most of the time, no keys are generated, it stuck at 194.29% with CORS issue when running the code locally, on the (your) hosted site, it just stuck at ~194%

**Comment by poria129** [comment]
There is another generator that generates codes very slowly, but it will include all the numbers you selected. However, as I mentioned, it's very slow. I prefer this one because it's much faster.

**Comment by ShafiqSadat** [comment]
Fixed!
