### ISSUE TITLE
Dark-mode version of styles.css

### ISSUE THREAD

**Issue by Firehawk52** [ShafiqSadat/HamsterKeyGenWeb#7]
[styles.zip](https://github.com/user-attachments/files/16656980/styles.zip)

**Comment by ShafiqSadat** [comment]
Can you open a Pull request?

also implement Dark/Light version in same file?

**Comment by Firehawk52** [comment]
Not sure I have access to do that. But here is stylesheet (with dark and light) with added code in HTML (just after source button) and added code to the .js-file, so you can just toggle. You can customize as you like

[styles.zip](https://github.com/user-attachments/files/16661645/styles.zip)

**Comment by Fakhrillo** [comment]
Hey guys, just wandering how to turn dark mode one? If it's possible can you add a button or toggle to add that feature? Thanks for the hard work guys

**Comment by Icloner** [comment]
> Can you open a Pull request?
> 
> also implement Dark/Light version in same file?



> Can you open a Pull request?
> 
> also implement Dark/Light version in same file?

Hello,

I can professionally add both dark mode and the main mode for you

**Comment by Icloner** [comment]
> Can you open a Pull request?
> 
> also implement Dark/Light version in same file?

Hello,

I can professionally add both dark mode and the main mode for you.
![1](https://github.com/user-attachments/assets/a90169d6-6caa-4ce7-8d20-4179867c334e)

**Comment by Firehawk52** [comment]
I already submitted the code - just implement it

**Comment by ShafiqSadat** [comment]
Please open a PR!

**Comment by Firehawk52** [comment]
> Please open a PR!

Don't have access - but I made a fork

**Comment by ShafiqSadat** [comment]
Added!

**Comment by Icloner** [comment]
Hello Dear Friend,

I hope this message finds you well.

I am reaching out to seek your esteemed guidance on how to obtain the following credentials:

- appToken:
- promoId:

This information is crucial for my ongoing project, and I would greatly appreciate any assistance you could provide. Your expert advice will be invaluable in helping me proceed with confidence.

Thank you in advance for your time and consideration. I look forward to your prompt and informative response.

Kind regards,
